"""Generation seeds: curated clause groups + coverage metadata.

The LLM (DeepEval Synthesizer + enrichment) generates the question and answer text;
these seeds fix the grounding (clause IDs), the A/B/C category, coverage
(topic/persona/difficulty/question_type), the verified C classifications
(ambiguity_type/external_references), and Hyde seed-question exemplars for few-shot.

Auto-generated from the curated specs; edit here going forward.
"""

from __future__ import annotations

SEEDS: list[dict] = [
    {'key': 'A01', 'category': 'A', 'cids': [['PartA/3.4', 'within thr', 'primary', 'states the daily reconciliation duty and the 3-day reporting window']], 'topic': 'settlements', 'persona': 'finance_ops', 'difficulty': 'easy', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A02', 'category': 'A', 'cids': [['PartA/3.3', 'ten (10) days', 'primary', 'sets the 10-day invoice dispute window and deemed-acceptance rule']], 'topic': 'fees', 'persona': 'finance_ops', 'difficulty': 'easy', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A04', 'category': 'A', 'cids': [['PartA/7.2', 'one (1) month fees', 'primary', "caps aggregate liability at one month's fees"]], 'topic': 'liability', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A05', 'category': 'A', 'cids': [['PartA/12.3', 'twenty-four (24) hours', 'primary', 'sets the 24-hour breach notification deadline']], 'topic': 'data_protection', 'persona': 'engineer', 'difficulty': 'easy', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A06', 'category': 'A', 'cids': [['PartA/12.4', 'full card credentials', 'primary', 'prohibits storing full card credentials']], 'topic': 'data_protection', 'persona': 'engineer', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A07', 'category': 'A', 'cids': [['PartA/2.20', 'convenience fee', 'primary', 'permits a merchant-imposed convenience fee with liability on the merchant']], 'topic': 'fees', 'persona': 'founder', 'difficulty': 'easy', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A08', 'category': 'A', 'cids': [['PartA/2.21', 'prior written consent', 'primary', 'requires prior written consent for third-party providers']], 'topic': 'prohibited_businesses', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A09', 'category': 'A', 'cids': [['PartA/9.3', 'fines, penalties', 'primary', 'makes the merchant reimburse card-network fines from its non-compliance']], 'topic': 'chargebacks_fraud', 'persona': 'finance_ops', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A12', 'category': 'A', 'cids': [['PartA/6.1', 'as is', 'primary', 'disclaims warranties; services provided as-is']], 'topic': 'liability', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A13', 'category': 'A', 'cids': [['PartA/8.1', 'indemnify and hold', 'primary', "establishes the merchant's indemnity obligation"]], 'topic': 'liability', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A14', 'category': 'A', 'cids': [['PartA/2.25', 'deducting the amount from Your settlement', 'primary', 'permits recovery of attributable penalties via settlement deduction']], 'topic': 'settlements', 'persona': 'finance_ops', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A16', 'category': 'A', 'cids': [['PartA/3.1', 'MDR charges', 'primary', 'states fees include MDR for payment instruments']], 'topic': 'fees', 'persona': 'finance_ops', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A17', 'category': 'A', 'cids': [['PartA/14.3', 'additional fees', 'primary', "reserves Razorpay's right to revise/introduce fees"]], 'topic': 'fees', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A18', 'category': 'A', 'cids': [['PartA/7.2', 'one (1) month fees', 'primary', "corrects the false premise: the cap is one month's fees, not annual"]], 'topic': 'liability', 'persona': 'cto', 'difficulty': 'hard', 'question_type': 'adversarial_false_premise', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A19', 'category': 'A', 'cids': [['PartA/3.3', 'ten (10) days', 'primary', 'corrects the false premise: the dispute window is 10 days, not 30']], 'topic': 'fees', 'persona': 'finance_ops', 'difficulty': 'medium', 'question_type': 'adversarial_false_premise', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'A20', 'category': 'A', 'cids': [['PartA/12.4', 'full card credentials', 'primary', 'corrects the false premise: storing full card credentials is prohibited']], 'topic': 'data_protection', 'persona': 'engineer', 'difficulty': 'medium', 'question_type': 'adversarial_false_premise', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B01', 'category': 'B', 'cids': [['PartA/16.1', 'immediately suspend Services and settlement', 'primary', 'grants the right to suspend settlement on specified triggers']], 'topic': 'chargebacks_fraud', 'persona': 'support_lead', 'difficulty': 'hard', 'question_type': 'conditional', 'origin': 'seed_anchor', 'review_status': 'human_verified', 'exemplar': 'A customer says their card was used without their permission. Can Razorpay hold our settlement money?'},
    {'key': 'B02', 'category': 'B', 'cids': [['PartA/3.1', 'MDR charges', 'primary', 'fees and included MDR vary by payment instrument']], 'topic': 'fees', 'persona': 'finance_ops', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B03', 'category': 'B', 'cids': [['PartA/2.20', 'convenience fee', 'primary', 'permits convenience fee with merchant bearing resulting losses']], 'topic': 'fees', 'persona': 'founder', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B04', 'category': 'B', 'cids': [['PartA/2.21', 'prior written consent', 'primary', 'third-party providers require prior written consent / approved orchestration']], 'topic': 'prohibited_businesses', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B05', 'category': 'B', 'cids': [['PartA/3.4', 'within thr', 'primary', 'discrepancies must be reported within three (3) days']], 'topic': 'settlements', 'persona': 'finance_ops', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B06', 'category': 'B', 'cids': [['PartA/3.3', 'ten (10) days', 'primary', 'invoice disputes must be raised within ten (10) days']], 'topic': 'fees', 'persona': 'finance_ops', 'difficulty': 'easy', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B07', 'category': 'B', 'cids': [['PartA/2.7', 'Central KYC Records', 'primary', "Razorpay's CDD process and KYC retrieval rights"]], 'topic': 'kyc_onboarding', 'persona': 'finance_ops', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B08', 'category': 'B', 'cids': [['PartA/2.14', 'bona fide business', 'primary', 'use must match registered categories and be lawful']], 'topic': 'prohibited_businesses', 'persona': 'founder', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B09', 'category': 'B', 'cids': [['PartA/2.25', 'deducting the amount from Your settlement', 'primary', 'recovery via settlement deduction for attributable penalties']], 'topic': 'settlements', 'persona': 'finance_ops', 'difficulty': 'hard', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B10', 'category': 'B', 'cids': [['PartA/8.1', 'indemnify and hold', 'primary', 'indemnity scope is tied to your breach / legal violations']], 'topic': 'liability', 'persona': 'cto', 'difficulty': 'hard', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B11', 'category': 'B', 'cids': [['PartA/14.3', 'additional fees', 'primary', 'additional fees may apply for value-added services']], 'topic': 'fees', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B12', 'category': 'B', 'cids': [['PartA/16.1', 'immediately suspend Services and settlement', 'primary', 'lists multiple suspension triggers']], 'topic': 'suspension_termination', 'persona': 'support_lead', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B13', 'category': 'B', 'cids': [['PartA/2.9', 'refund requests', 'primary', 'after-sales/refund obligations rest with the merchant']], 'topic': 'refunds', 'persona': 'support_lead', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B14', 'category': 'B', 'cids': [['PartA/12.3', 'twenty-four (24) hours', 'primary', '24-hour duty applies to security breaches / unauthorized access']], 'topic': 'data_protection', 'persona': 'engineer', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B15', 'category': 'B', 'cids': [['PartA/7.2', 'one (1) month fees', 'primary', "cap is one month's fees for the specific service at issue"]], 'topic': 'liability', 'persona': 'cto', 'difficulty': 'hard', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B16', 'category': 'B', 'cids': [['PartA/16.1', 'immediately suspend Services and settlement', 'primary', 'permits suspension of settlement during disputes'], ['PartA/9.3', 'fines, penalties', 'supporting', 'card-network rule outcomes can attach costs to the merchant']], 'topic': 'chargebacks_fraud', 'persona': 'support_lead', 'difficulty': 'hard', 'question_type': 'multi_hop', 'origin': 'seed_anchor', 'review_status': 'human_verified', 'exemplar': 'A customer is disputing a charge they say they never authorized. What happens to our money?'},
    {'key': 'B17', 'category': 'B', 'cids': [['PartA/16.1', 'immediately suspend Services and settlement', 'primary', 'the suspension right is trigger-based, not amount-based, so the premise needs checking']], 'topic': 'settlements', 'persona': 'support_lead', 'difficulty': 'hard', 'question_type': 'adversarial_false_premise', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B18', 'category': 'B', 'cids': [['PartA/14.6', 'at Your own risk', 'primary', 'cross-border / card-not-present transactions are at the merchant risk; specifics depend on instrument and geography']], 'topic': 'cross_border', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B19', 'category': 'B', 'cids': [['PartA/2.22', 'marketplace', 'primary', 'marketplace / seller-onboarding rules apply depending on how the platform is structured']], 'topic': 'kyc_onboarding', 'persona': 'founder', 'difficulty': 'hard', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'B20', 'category': 'B', 'cids': [['PartA/9.3', 'fines, penalties', 'primary', 'whether a chargeback cost falls on the merchant depends on attribution to its non-compliance / the network ruling']], 'topic': 'chargebacks_fraud', 'persona': 'finance_ops', 'difficulty': 'hard', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed'},
    {'key': 'C01', 'category': 'C', 'cids': [['PartA/14.10', 'real money online gaming', 'primary', 'prohibits using the Services for real money online gaming as defined by an external Act']], 'topic': 'gaming', 'persona': 'founder', 'difficulty': 'hard', 'question_type': 'conditional', 'origin': 'seed_anchor', 'review_status': 'human_verified', 'ambiguity_type': 'external_cross_reference', 'external_references': [['Promotion and Regulation of Online Gaming Act, 2025', None, "defines 'online money game' which clause 14.10 relies on but does not reproduce"], ['State-level gaming regulations', None, 'skill-vs-chance treatment varies by state and is not addressed in the ToS']], 'escalation_reason': 'The permitted/prohibited boundary turns on external law not defined in the ToS.', 'exemplar': "We're building a real-money gaming feature. Can we use Razorpay to collect payments for it?"},
    {'key': 'C02', 'category': 'C', 'cids': [['PartA/16.1', 'immediately suspend Services and settlement', 'primary', 'grants an immediate right to suspend settlement but states no maximum hold duration']], 'topic': 'suspension_termination', 'persona': 'cto', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'seed_anchor', 'review_status': 'human_verified', 'ambiguity_type': 'silent', 'external_references': [], 'escalation_reason': 'The document does not bound the fund-hold duration, so timelines must be confirmed directly with Razorpay.', 'exemplar': 'Razorpay suspended our account under the suspension clause. How long can they hold our funds?'},
    {'key': 'C03', 'category': 'C', 'cids': [['PartA/14.6', 'at Your own risk', 'primary', "states cross-border and CNP transactions are undertaken at the merchant's own risk"]], 'topic': 'cross_border', 'persona': 'cto', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'external_cross_reference', 'external_references': [['RBI / FEMA cross-border payment regulations', None, 'govern cross-border payment obligations the ToS assumes but does not detail']], 'escalation_reason': 'Cross-border specifics depend on external regulation not detailed in the ToS.'},
    {'key': 'C04', 'category': 'C', 'cids': [['PartA/2.7', 'Central KYC Records', 'primary', 'ties KYC retrieval to an external CKYCR system and regulator/Facility Provider requirements']], 'topic': 'kyc_onboarding', 'persona': 'finance_ops', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'external_cross_reference', 'external_references': [['RBI Master Directions on KYC', None, 'define KYC/CDD scope that clause 2.7 relies on but does not reproduce'], ['Central KYC Records (CKYCR)', None, 'external registry from which records may be retrieved']], 'escalation_reason': "The scope of KYC obligations is set by external regulation and Razorpay's discretion."},
    {'key': 'C05', 'category': 'C', 'cids': [['PartA/9.3', 'fines, penalties', 'primary', 'card-network non-compliance can attach fines/penalties recoverable from you'], ['PartA/16.1', 'immediately suspend Services and settlement', 'supporting', 'settlement can be suspended during disputes']], 'topic': 'chargebacks_fraud', 'persona': 'finance_ops', 'difficulty': 'hard', 'question_type': 'multi_hop', 'origin': 'seed_anchor', 'review_status': 'human_verified', 'ambiguity_type': 'external_cross_reference', 'external_references': [['RBI notification on customer protection (limiting liability in unauthorised transactions)', None, 'governs resolution of unauthorised/fraud transactions referenced by the ToS'], ['NPCI fraud guidelines / thresholds', None, 'determine fraud-handling outcomes not defined in the ToS']], 'escalation_reason': 'Resolution depends on external network rules and RBI notifications, not the ToS alone.', 'exemplar': 'A fraudulent transaction was already settled to us. What happens now under the Razorpay terms?'},
    {'key': 'C06', 'category': 'C', 'cids': [['PartA/7.2', 'one (1) month fees', 'primary', 'caps liability but is silent on interaction with consequential losses/carve-outs']], 'topic': 'liability', 'persona': 'cto', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'vague', 'external_references': [], 'escalation_reason': 'Interaction between the contractual cap and non-excludable statutory liability is not resolved in the ToS.'},
    {'key': 'C07', 'category': 'C', 'cids': [['PartA/11.1', 'control', 'primary', "force-majeure section is present but does not bound the event's duration"]], 'topic': 'liability', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'silent', 'external_references': [], 'escalation_reason': 'No maximum force-majeure duration or recourse trigger is defined in the ToS.'},
    {'key': 'C08', 'category': 'C', 'cids': [['PartA/13.1', 'anti-bribery', 'primary', 'requires compliance with external anti-bribery/anti-corruption laws without enumerating them']], 'topic': 'prohibited_businesses', 'persona': 'founder', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'external_cross_reference', 'external_references': [['Applicable anti-bribery and anti-corruption laws', None, 'the external statutes clause 13.1 incorporates by reference without listing'], ['Applicable sanctions laws', None, 'referenced in the Anti-Bribery and Sanctions Laws section']], 'escalation_reason': 'The applicable legal standard is defined by external statutes, not the ToS.'},
    {'key': 'C09', 'category': 'C', 'cids': [['PartA/12.4', 'full card credentials', 'primary', 'prohibits storing card credentials but is silent on downstream-processor breach handling']], 'topic': 'data_protection', 'persona': 'engineer', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'vague', 'external_references': [], 'escalation_reason': 'Downstream-breach obligations are not specified in the ToS and depend on external data-protection law.'},
    {'key': 'C10', 'category': 'C', 'cids': [['PartA/14.3', 'additional fees', 'primary', 'reserves a broad right to revise fees without stated limits']], 'topic': 'fees', 'persona': 'cto', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'silent', 'external_references': [], 'escalation_reason': 'No cap, frequency limit, or notice mechanism for fee changes is defined in the ToS.'},
    {'key': 'C11', 'category': 'C', 'cids': [['PartA/2.25', 'deducting the amount from Your settlement', 'primary', 'allows recovery of attributable penalties but does not define how attribution is determined']], 'topic': 'settlements', 'persona': 'finance_ops', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'vague', 'external_references': [], 'escalation_reason': 'The attribution and quantification process for recovered penalties is undefined in the ToS.'},
    {'key': 'C12', 'category': 'C', 'cids': [['PartA/3.5', '194H', 'primary', 'ties tax reimbursement to external Income Tax Act provisions and Form 16-A']], 'topic': 'taxes_gst', 'persona': 'finance_ops', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'external_cross_reference', 'external_references': [['Section 194H, Income Tax Act, 1961', 'Section 194H', 'governs the TDS mechanics the reimbursement depends on'], ['Form 16-A', 'Form 16-A', 'the TDS certificate that must be furnished to obtain reimbursement']], 'escalation_reason': 'The reimbursement process is governed by external tax law the ToS does not detail.'},
    {'key': 'C13', 'category': 'C', 'cids': [['PartA/2.23', 'blacklist', 'primary', "permits blacklisting end users at Razorpay's discretion without stated criteria or appeal"]], 'topic': 'suspension_termination', 'persona': 'support_lead', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'silent', 'external_references': [], 'escalation_reason': 'Blacklisting criteria and any appeal mechanism are not defined in the ToS.'},
    {'key': 'C14', 'category': 'C', 'cids': [['PartA/2.22', 'marketplace', 'primary', 'imposes seller-onboarding constraints by reference to external Master Directions']], 'topic': 'kyc_onboarding', 'persona': 'founder', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'external_cross_reference', 'external_references': [['RBI Master Directions (Payment Aggregators)', None, "define 'e-commerce marketplace' and onboarding obligations referenced by clause 2.22"]], 'escalation_reason': 'Marketplace obligations are defined by external RBI Master Directions, not the ToS.'},
    {'key': 'C15', 'category': 'C', 'cids': [['PartA/2.14', 'bona fide', 'primary', 'use is limited to lawful, registered business activities']], 'topic': 'prohibited_businesses', 'persona': 'founder', 'difficulty': 'hard', 'question_type': 'conditional', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'external_cross_reference', 'external_references': [['RBI / SEBI guidance on virtual digital assets', None, 'governs permissibility of crypto/NFT payments not resolved by the ToS']], 'escalation_reason': 'Permissibility of crypto/NFT products depends on external regulation and Razorpay confirmation.'},
    {'key': 'C16', 'category': 'C', 'cids': [['PartA/16.1', 'immediately suspend Services and settlement', 'supporting', 'termination/suspension rights exist but survival scope/duration is not detailed here']], 'topic': 'suspension_termination', 'persona': 'cto', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'vague', 'external_references': [], 'escalation_reason': 'The scope and duration of surviving obligations after termination is not fully specified in the ToS.'},
    {'key': 'C17', 'category': 'C', 'cids': [['PartA/2.9', 'refund requests', 'primary', 'places after-sales/refund handling on the merchant but is silent on dispute-resolution timelines and chargeback interaction']], 'topic': 'refunds', 'persona': 'support_lead', 'difficulty': 'medium', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'silent', 'external_references': [], 'escalation_reason': 'The ToS does not define refund dispute timelines or how they interact with chargebacks.'},
    {'key': 'C18', 'category': 'C', 'cids': [['PartA/12.3', 'twenty-four (24) hours', 'primary', 'requires breach notification within 24 hours but does not define the severity threshold that triggers it']], 'topic': 'data_protection', 'persona': 'engineer', 'difficulty': 'hard', 'question_type': 'factual', 'origin': 'synthesized', 'review_status': 'unreviewed', 'ambiguity_type': 'vague', 'external_references': [], 'escalation_reason': 'What constitutes a reportable breach (severity threshold) is not defined in the ToS.'},
]
